image: node:latest

cache:
  paths:
    - node_modules/

pages:
  only:
    - publish
  script:
    - npm install
    # GitLab doesn't run post install hooks. Normally npm install would do this
    - npm run snowpack
    - cd ssr
    - npm install
    - cd -
    # Fix URL since GitLab hosts at a subdomain
    - sed -i 's|/web_modules/|/stayknit/web_modules/|' .babelrc.json
    - npm run build
    - npm run ssr
    - mv serve public
  artifacts:
    paths:
      - public/
